# Generated by Django 4.2.1 on 2023-05-07 09:46

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Word",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新日")),
                ("name", models.CharField(max_length=200, verbose_name="見出し語")),
                ("meaning", models.CharField(max_length=200, verbose_name="意味")),
                (
                    "phonetic_spelling",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="発音記号"
                    ),
                ),
                ("example_sentence", models.TextField(verbose_name="例文")),
            ],
            options={
                "verbose_name": "単語",
                "verbose_name_plural": "単語",
                "ordering": ["name"],
            },
        ),
    ]
